In [ ]:
import numpy as np
import pandas as pd
import io
import string

In [ ]:
data = """surface (square feet),bedrooms,floors,price (k USD)
flat1,620,1,1,244
flat2,3280,4,2,671
flat3,1900,2,2,504
flat4,1320,3,3,510"""

In [ ]:
df = pd.read_csv(io.StringIO(data))
df

surface (square feet)  bedrooms  floors  price (k USD)
flat1                    620         1       1            244
flat2                   3280         4       2            671
flat3                   1900         2       2            504
flat4                   1320         3       3            510

In [ ]:
# features
values = np.array([[620,1,1],[3280,4,2],[1900,2,2],[1320,3,3]])
values

array([[ 620,    1,    1],
       [3280,    4,    2],
       [1900,    2,    2],
       [1320,    3,    3]])

In [ ]:
# theta 0
x0 = np.ones((4,1))
x0

array([[1.],
       [1.],
       [1.],
       [1.]])

In [ ]:
# features
X = np.hstack((x0,values))
X

array([[1.00e+00, 6.20e+02, 1.00e+00, 1.00e+00],
       [1.00e+00, 3.28e+03, 4.00e+00, 2.00e+00],
       [1.00e+00, 1.90e+03, 2.00e+00, 2.00e+00],
       [1.00e+00, 1.32e+03, 3.00e+00, 3.00e+00]])

In [ ]:
# target
Y = np.array([[244,671,504,510]]).T
Y

array([[244],
       [671],
       [504],
       [510]])

In [ ]:
X_inv = np.linalg.inv(X)
X_inv

array([[ 1.64516129e+00,  4.42419702e-17, -2.90322581e-01,
        -3.54838710e-01],
       [-5.37634409e-04, -2.50426246e-19,  1.07526882e-03,
        -5.37634409e-04],
       [ 3.70967742e-01,  5.00000000e-01, -1.24193548e+00,
         3.70967742e-01],
       [-6.82795699e-01, -5.00000000e-01,  8.65591398e-01,
         3.17204301e-01]])

In [ ]:
I4 = np.matmul(X_inv, X)
I4

array([[ 1.00000000e+00, -5.10702591e-14, -5.55111512e-17,
        -2.77555756e-16],
       [-3.25260652e-19,  1.00000000e+00, -8.67361738e-19,
        -4.33680869e-19],
       [ 3.33066907e-16,  5.07149878e-13,  1.00000000e+00,
         3.33066907e-16],
       [-2.77555756e-16, -6.10622664e-13, -7.21644966e-16,
         1.00000000e+00]])

In [ ]:
np.allclose(X_inv, X)

False

In [ ]:
theta = np.matmul(X_inv, Y)
theta

array([[ 74.12903226],
       [  0.13655914],
       [-10.72580645],
       [ 95.93010753]])

In [ ]:
# Define X5
X5 = np.array([[1, 3000, 5, 1]])
# Compute Y5
Y5 = np.matmul(X5,theta)
# You should find a Price of 526,000 $
Y5

array([[1.19489134e+10]])

In [ ]:
# Create the new matrix of features X of shape (5,4)
new_values = np.array([[620,1,1],[3280,4,2],[1900,2,2],[1320,3,3],[3000, 5, 1]])
ones = np.ones((5,1))
X = np.hstack((ones, new_values))
print(X)
# Print the shape to double-check the shape is indeed (5,4)
X_t = X.T
X_t.shape

[[1.00e+00 6.20e+02 1.00e+00 1.00e+00]
 [1.00e+00 3.28e+03 4.00e+00 2.00e+00]
 [1.00e+00 1.90e+03 2.00e+00 2.00e+00]
 [1.00e+00 1.32e+03 3.00e+00 3.00e+00]
 [1.00e+00 3.00e+03 5.00e+00 1.00e+00]]


(4, 5)